### ISSUE TITLE
/api/breed/{breed}/images/random not working?

### ISSUE THREAD

**Issue by julian100004** [ElliottLandsborough/dog-ceo-api#1]
If i use **/api/breed/border/images/random** a.e i'm just getting "_Breed not found_". What can i do?

**Comment by julian100004** [comment]
**/api/breeds/image/random** working btw

**Comment by ElliottLandsborough** [comment]
Do you have a folder called '/api/img/border/' with at least one image in it?

**Comment by ElliottLandsborough** [comment]
On the live site the folder for borders is called '/api/img/border-collie' so to get a random border image you will have do go to https://dog.ceo/api/breed/collie/border/images/random.

I will be happy to accept a pull request if you would like to add different functionality.

**Comment by jigsawpieces** [comment]
@julian100004 if you want to find border collies you can access them here https://dog.ceo/api/breed/collie/border/images/random

**Comment by toddpress** [comment]
It's working in the future too-- [BAHA MEN REJOICE](https://dog.ceo/api/breeds/image/random)

**Comment by ElliottLandsborough** [comment]
Good work guys!
