### ISSUE TITLE
Request: random breed api call

### ISSUE THREAD

**Issue by BrettGoreham** [ElliottLandsborough/dog-ceo-api#12]
It would be cool if it was possible to ask for a random breed or a subset of the breeds list. 

https://dog.ceo/api/breeds/random
https://dog.ceo/api/breeds/random/5

With the result being a random breed names or 5.
 
Would code it myself but i dont know php :P

**Comment by ElliottLandsborough** [comment]
Good idea, and actually a pretty simple change.

I've added it to my to-do list and will close this issue when it's done.

**Comment by ElliottLandsborough** [comment]
@BrettGoreham the new endpoints have been added:

https://dog.ceo/api/breeds/list/all/random
https://dog.ceo/api/breeds/list/all/random/10

https://dog.ceo/api/breeds/list/random
https://dog.ceo/api/breeds/list/random/10

https://dog.ceo/api/breed/hound/list/random
https://dog.ceo/api/breed/hound/list/random/3

**Comment by BrettGoreham** [comment]
Cool thats awesome thanks :D

**Comment by BrettGoreham** [comment]
Awesome :D
the difference between these two
https://dog.ceo/api/breeds/list/random
https://dog.ceo/api/breeds/list/all/random

is that all will show sub breeds?

**Comment by ElliottLandsborough** [comment]
Yes.

You can see documentation for all the endpoints here: https://github.com/ElliottLandsborough/dog-ceo-api/blob/master/readme.md
