### ISSUE TITLE
404 Errors don't have CORS headers

### ISSUE THREAD

**Issue by bookcasey** [ElliottLandsborough/dog-ceo-api#13]
If you ping an invalid URL, you don't get a 404, you get a CORS error.

```
fetch('https://dog.ceo/api/breeds/list/x')
  .then(res => res.json())
  .then(data =>console.log(data));;

**Comment by ElliottLandsborough** [comment]
Thanks for reporting it, and yep, this is another problem with the current (and quite frankly rushed) code base.

I've almost finished doing a rewrite which fixes this issue among other things.

I will update the status here when it is done.

**Comment by ElliottLandsborough** [comment]
@bookcasey this is fixed, see screenshot.
![headers](https://user-images.githubusercontent.com/1583854/59345864-f4555a80-8d08-11e9-8a21-f44696be51ba.png)
