### ISSUE TITLE
List of all breeds returns as object, not array

### ISSUE THREAD

**Issue by kazi05** [ElliottLandsborough/dog-ceo-api#26]
If we call `https://dog.ceo/api/breeds/list/all` in response "message" key has object type, not array. Do you propose to handle each value separately?

![Снимок экрана 2020-08-24 в 18 04 12](https://user-images.githubusercontent.com/26439900/91061043-5c553f80-e634-11ea-8391-8eb9fd52cabb.png)

**Comment by jimmyadaro** [comment]
If you're looking for something this:

![fully list of breeds and sub-breeds](https://i.imgur.com/7t16Nnh.png)

I just made this script to get all the info together:

```jsx
const data_raw = res.data.message // <= From the API response to "GET /breeds/list/all"
let data_all = []

for (let i in data_raw) {
  // If item has some length, then it includes an array - a.k.a. sub-breed(s)
  if (data_raw[i].length !== 0) {
    if (`${data_raw[i]}`.includes(",")) {
      const split_breeds = `${data_raw[i]}`.split(',')
      split_breeds.forEach((item) => {
        data_all.push(`${item} ${i}`)
      });
    } else {
      data_all.push(`${data_raw[i]} ${i}`)
    }
  } else {
    // Otherwise, the name will be just the breed
    data_all.push(`${i}`)
  }
}

console.log(data_all)
// (141) ["affenpinscher", "african", "airedale", "akita", "appenzeller", ...]
```

This way you can even control how it's displayed (e.g. _breed_ before _sub-breed_ or viceversa) 

Hope it helps!!

**Comment by ElliottLandsborough** [comment]
Thanks for the help!

I agree that some of the outputs are not the most optimal, but it would be worse to change them as it will break compatibility with anything that is already out there.
