### ISSUE TITLE
Breed names with spaces do not work.

### ISSUE THREAD

**Issue by laxuscullen** [ElliottLandsborough/dog-ceo-api#28]
https://dog.ceo/api/breed/Golden%20Retriever/images/random
https://dog.ceo/api/breed/Golden Retriever/images/random

**Comment by ElliottLandsborough** [comment]
Yes you are correct, the API does not support spaces.

You can see a list of possible breeds here: https://dog.ceo/dog-api/documentation/

The url that you need is this one: https://dog.ceo/api/breed/retriever/golden/images/random

Here is a codepen example: https://codepen.io/elliottlan/pen/LYReELj

**Comment by laxuscullen** [comment]
Wow this is very weird, since I only saw your breed's endpoint and the example shows the output using options where your select the breed name and it shows the url I mentioned as an example

**Comment by laxuscullen** [comment]
I was doing a dynamic search by simply putting the breed name in the basic url (which works for all breed names without spaces) and now this seems impossible.

**Comment by ElliottLandsborough** [comment]
Here is an example of how to convert the breeds into human readable format: https://codepen.io/elliottlan/pen/LYReELj

Once you have the breeds in human readable format you can use something like the HTML5 datalist element for searching: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
