### ISSUE TITLE
/api/breeds/image/random returns 403 Forbidden

### ISSUE THREAD

**Issue by strukteon** [ElliottLandsborough/dog-ceo-api#4]
When trying to fetch a random Image the server returns a 403 Forbidden error

**Comment by jigsawpieces** [comment]
https://dog.ceo/api/breeds/image/random

Is returning results for me?

**Comment by strukteon** [comment]
![grafik](https://user-images.githubusercontent.com/16156188/40391616-36304638-5e19-11e8-91f6-a65d83410341.png)

**Comment by edc0der** [comment]
As @jigsawpieces indicates, the call to [https://dog.ceo/api/breeds/image/random](https://dog.ceo/api/breeds/image/random) seems to be working properly. 
Clicking on the link or putting the URL in a GET request on Postman retrieves the expected result. 

If you provide details on how you are performing the request will help determine if there's an issue elsewhere, which seems to be the case.

**Comment by ElliottLandsborough** [comment]
@strukteon it could be cloudflare blocking you for some reason.

Can you provide me with all the request headers you are sending along with your user agent please?

**Comment by Derppening** [comment]
I have the same problem. When trying to use Kotlin to access the API
```kotlin
URL("https://dog.ceo/api/breeds/image/random").openConnection().getInputStream().bufferedReader().readText().also(::println)
```
It returns this:
```
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://dog.ceo/api/breeds/image/random
```

However, if I try to set the user agent first (using Chrome 67 as an example):
```kotlin
URL("https://dog.ceo/api/breeds/image/random").openConnection().also {
    it.setRequestProperty("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36")
}.getInputStream().bufferedReader().readText().also(::println)
```
It works fine:
```
{"status":"success","message":"https:\/\/images.dog.ceo\/breeds\/african\/n02116738_7060.jpg"}
```

So maybe the problem is that something blocks the API access when there is no user agent?

**Comment by ElliottLandsborough** [comment]
@Derppening I have no idea how to use kotlin but I think I may have fixed it - can you try the request again with no user agent please?

Thanks.

**Comment by Derppening** [comment]
@ElliottLandsborough It works just fine now.

**Comment by ElliottLandsborough** [comment]
In case anyone comes here wanting to know how I fixed it: https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-

Issue closed.
