### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by XinranCao** [ElliottLandsborough/dog-ceo-api#44]
I got server error when fetching from "https://dog.ceo/api/breeds/image/random". 

{
    "status": "error",
    "message": "Server error: `GET https:\/\/api.dog.ceo\/breeds\/list\/all` resulted in a `502 Bad Gateway` response:\n{\"message\": \"Internal server error\"}\n with code: 502",
    "code": 500
}

Is this a temporary break down?

**Comment by ElliottLandsborough** [comment]
Yes, this is temporary. It will be fixed in the next few days. Thank you for reporting it. I will post here as soon as it is fixed.

**Comment by ElliottLandsborough** [comment]
@XinranCao This has been fixed, the endpoints should slowly come back online as the caches refresh.
