### ISSUE TITLE
[Bug] Dropdown in Breed List is not Sorted.

### ISSUE THREAD

**Issue by lonemohsin33** [ElliottLandsborough/dog-ceo-api#45]
**Describe the bug.**
if we navigate to dog-api/breeds-list in the dropdown the list of breeds should be sorted. but it is not. 

**Screenshot.**
![Screenshot from 2023-09-28 13-36-18](https://github.com/ElliottLandsborough/dog-ceo-api/assets/79997126/bbbaa1e1-bfa4-4d1b-affb-7f3332566ea6)

**Fix**
Sort the list of breeds when populating it.

**Comment by jigsawpieces** [comment]
@lonemohsin33 it is sorted by primary breed, eg. "bulldog" instead of the breed variant.

**Comment by lonemohsin33** [comment]
> @lonemohsin33 it is sorted by primary breed, eg. "bulldog" instead of the breed variant.

ok closing it!
