### ISSUE TITLE
Missing image for Coton-Detulear

### ISSUE THREAD

**Issue by nodes777** [ElliottLandsborough/dog-ceo-api#5]
Hey thanks for making this! I'm using it to learn React and have got a little React app going at [taylornodell.com/dogsdogsdogs](taylornodell.com/dogsdogsdogs). However, I'm getting a 404 for the following image. Not a high priority fix, but thought you might want to know.

[https://images.dog.ceo/breeds/coton-detulear/IMAG1063.jpeg](https://images.dog.ceo/breeds/coton-detulear/IMAG1063.jpeg)

**Comment by ElliottLandsborough** [comment]
This issue has been fixed, thanks for reporting it!
