### ISSUE TITLE
Add endpoint "/breed/{breed}/images/random/{number}"

### ISSUE THREAD

**Issue by alexluong** [ElliottLandsborough/dog-ceo-api#6]
Hey guys,

First of all, just wanna say that I love this API. I had a lot of fun building small projects using it.

I think we should add this endpoint "/breed/{breed}/images/random/{number}". To me, it seems like a common functionality. Hope somebody can make this happen. Thanks!!

**Comment by ElliottLandsborough** [comment]
Feature now exists, thanks for the good idea!

https://dog.ceo/api/breeds/image/random/3
https://dog.ceo/api/breed/affenpinscher/images/random/6
https://dog.ceo/api/breed/bulldog/french/images/random/7

**Comment by jigsawpieces** [comment]
Will update documentation site for this
