### ISSUE TITLE
Endpoints for Get Informations not working

### ISSUE THREAD

**Issue by IsmaelNascimento** [ElliottLandsborough/dog-ceo-api#7]
Endpoints:

1. https://dog.ceo/api/breed/breed/{breed} - Get information of breed
![getbreed](https://user-images.githubusercontent.com/19227867/44308926-caefca80-a394-11e8-9b9f-47ee8edb5b4a.JPG)

2. https://dog.ceo/api/breed/breed/{breed}/{breed2} - Get information of sub-breed
![getsubbreed](https://user-images.githubusercontent.com/19227867/44308928-d216d880-a394-11e8-8b3e-ed2f52b0996b.JPG)

Documentation of endpoints: https://github.com/ElliottLandsborough/dog-ceo-api

**Comment by ElliottLandsborough** [comment]
Hi Ismael, thanks for your feedback!

If you look at the link below you will see that yaml files have only been provided for 'spaniel' and 'cocker-spaniel'.

YAML Files: https://github.com/ElliottLandsborough/dog-ceo-api/tree/master/content/breed-info

Endpoint examples:
https://dog.ceo/api/breed/spaniel
https://dog.ceo/api/breed/spaniel/cocker

I do not have time to write descriptions for all the different breed types but if you would like to submit some descriptions via a pull request we would be happy to 'vet' them.

**Comment by imad93** [comment]
Hi,
Where is the contents folder? I can't find it, I might be interested in writing descriptions for breeds.

Cheers

**Comment by ElliottLandsborough** [comment]
This has been neglected since the rewrite a few months ago. I will get a new repository up ASAP so that people can contribute information files again.

**Comment by ElliottLandsborough** [comment]
@imad93 here is a repo: https://github.com/ElliottLandsborough/dog-ceo-api-content

Haven't had any time to write any guidelines - here's a few basic ones:

a) yaml file names must match breed names in api
b) yaml files must be valid yaml
c) required/only keys are 'name' and 'info'

It could probably be automated somehow assuming the source of the information is doesn't have any licensing issues.
