### ISSUE TITLE
api/breeds/image/random returns `null` for `message`

### ISSUE THREAD

**Issue by tikipatel** [ElliottLandsborough/dog-ceo-api#9]
https://dog.ceo/api/breeds/image/random is returning:

    {
        "status": "success",
        "message": null
    }

Expecting to return message that has link to a random photo.

**Comment by ElliottLandsborough** [comment]
@tikipatel this is fixed. Looks like I didn't text the last code well enough before deploying...

**Comment by tikipatel** [comment]
@ElliottLandsborough Thanks!

**Comment by ElliottLandsborough** [comment]
Thanks for reporting this by the way - it goes a long way towards helping us improve the service.
